apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-kube-app #it will refer to the pods with that name which created on deployment.yml
    tier: backend
  ports:
    - protocol: "TCP"
      port: 80  #outside world port
      targetPort: 8282 #target port in the container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-kube-app-deployment
  labels:
    group: deployment-example
spec:
  replicas: 1
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [ second-kube-app ] }
#    matchLabels:
#      app: second-kube-app #should be matched with label name
#      tier: backend
   #matchExpressions:
      #- { key: app, operator: In, values: [second-kube-app, first-kube-app]}

  template: # no need add kind:Pod it belong by default to POD object
    metadata:
      labels:
        app: second-kube-app
        tier: backend
    spec: # Pod config below
      containers:
        - name: second-node
          image: aliguliyev75/parking-adapter-jenkins-v3:5

