apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-kube-app #it will refer to the pods with that name which created on deployment.yml
    tier: backend
  ports:
    - protocol: "TCP"
      port: 80  #outside world port
      targetPort: 8282 #target port in the container
  type: LoadBalancer


