apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.metadata.namespace}}
spec:
  selector:
    app: {{ .Values.matchLabels.app }} #it will refer to the pods with that name which created on deployment.yml
    tier: {{ .Values.matchLabels.tier }}
  ports:
    - protocol: "TCP"
      port: 80  #outside world port
      targetPort: 8282 #target port in the container
  type: LoadBalancer


